# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17tLHHhBckihZsO1sx4MOM_tfcLknyILq
"""

import pandas as pd

# loading dataset and storing in train variable 
train=pd.read_csv('/content/sample_data/Data1.csv')

# display top 5 data 
print(train)

train['PM2.5-AVG'].hist()

# importing Randomforest 
from sklearn.ensemble import AdaBoostRegressor 
from sklearn.ensemble import RandomForestRegressor

# creating model 
m1 = RandomForestRegressor()

# seperating class label and other attributes 
train1 = train.drop(['air_quality_index'], axis=1) 
target = train['air_quality_index']

# Fitting the model 
m1.fit(train1, target)

# calculating the score and the score is  97.96360799890066% 
m1.score(train1, target) * 100

# predicting the model with other values (testing the data) 
# so AQI is 123.71 
m1.predict([[123, 45, 67, 34, 5, 0, 23,10]])

# defining model 
m2 = AdaBoostRegressor()

# Fitting the model 
m2.fit(train1, target)

# calculating the score and the score is  96.15377360010211% 
m2.score(train1, target)*100
# predicting the model with other values (testing the data) 
# so AQI is 94.42105263

# predicting the model with other values (testing the data) 
# so AQI is 94.42105263
m2.predict([[123, 45, 67, 34, 5, 0, 23, 10]])